// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlgviamuxtqboxuhmflv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sZ3ZpYW11eHRxYm94dWhtZmx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNjE3NzcsImV4cCI6MjA3MjgzNzc3N30.gMrmmRt0YjbjHYTCnX3sVHh8QgnmdFKdNMwIGwpuWc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});